spring.application.name=CSC3665Project1
spring.datasource.url=jdbc:ambari-node5.csc.calpoly.edu:5432/bwsproj1
spring.datasource.username=bwsproj1
spring.datasource.password=bws123
spring.datasource.driver-class-name=org.postgresql.Driver